### ISSUE TITLE
Possible p() & v() confusion

### ISSUE THREAD

**Issue by nhat-nguyen** [zeit/async-sema#13]
Looking at the source code and the examples, it seems to me that the library is using `p()` to signal/free up a resource, whereas `v()` is used to wait/"block" on the semaphore.

However, according to the definition of a semaphore, the uses of `p()` and `v()` are the other way around.  Some resources to verify are:
+ http://www.cs.ucsb.edu/~rich/class/cs170/notes/Semaphores/index.html
+ https://www.student.cs.uwaterloo.ca/~cs343/documents/notes.pdf (counting semaphore, page 104)

Please let me know if I'm misunderstanding the use case here. :)

**Comment by OlliV** [comment]
Yes you are absolutely correct, the traditional meaning of the terms is unfortunately mixed in this library. However if you think the letters could mean V = verhogen = increase and P = passeren = pass, then we can build a meaningful explanation for the function names. As you probably have noted the implementation is based on a fixed number of tokens distributed to the consumers. Now `v()` increases the number of registered consumers (either returns a token or puts the consumer to a queue waiting for a token), and `p()` clearly passes the token back to the Semaphore and eventually to the next waiter in the queue.

Retrospectively thinking I should have probably never used single letter function names anyway but something like `acquire()` and `release()`, that would have been a lot more self-explanatory.

**Comment by nhat-nguyen** [comment]
Thanks for the confirmation. Any chance the API would be updated with more standard names?
