### ISSUE TITLE
broken typescript definition

### ISSUE THREAD

**Issue by mooyoul** [zeit/async-sema#15]
Hi all, currently typescript definition seems broken, typescript compiler complains about malformed type definition file (`.d.ts`) syntax.

maybe it's off topic, I love this package. so i've migrated async-sema package to typescript. i'd like to discuss about publishing typescript version of async-sema. should i publish typescript version of async-sema package as individual package? or just send PR to this repo? Please kindly give me your advice. Thanks :)

**Comment by OlliV** [comment]
I'd prefer fixing the type definitions but I'm open to alternative solutions. The most important thing to me is that I can install this from npm and it works with the latest Node.js.

**Comment by k06a** [comment]
@OlliV installed from fork:
```
"async-sema": "https://github.com/dsabanin/async-sema",
```
