### ISSUE TITLE
IE 11 Support

### ISSUE THREAD

**Issue by HaveSpacesuit** [zeit/async-sema#39]
When adding this to a project, my app no longer loads in IE 11. I can't find any polyfills which alleviate the problem.

Has anyone had success running in IE?

**Comment by OlliV** [comment]
You could try changing this to `ES5`
 https://github.com/zeit/async-sema/blob/95cf8e48e990f1a866fd234f34b6f60c97afaeb2/tsconfig.json#L15

We once merged this PR but it made the package a lot bigger than we liked:
https://github.com/zeit/async-sema/pull/32

**Comment by HaveSpacesuit** [comment]
I needed to have Babel do it's thing to the package for it to work in IE. By default, we were excluding node_modules from compilation. I update our webpack config to something like this, which solved the issue.
```js
exclude: function(modulePath) {
            return (
              /node_modules/.test(modulePath) && !/async-sema/.test(modulePath)
            );
          },
```

**Comment by OlliV** [comment]
might be worth of adding this to the readme just in case.
