### ISSUE TITLE
What is the `nr` variable?

### ISSUE THREAD

**Issue by yifeikong** [zeit/async-sema#8]
sorry to interrupt. what does `nr` stands for, I thought it was `num of resource`, but then what is the `capacity` variable?

**Comment by OlliV** [comment]
`nr` is for the number of tokens/resources and `capacity` can be used to preallocate a bigger queue for waiters. For example if you are going to do something like:

```
// Make a sema for 5 concurrent operations with a preallocated queue length.
const s = new Sema(5, { capacity: arr.length });
arr.map(async (v) => {
  await s.v();
  <do something>
}
```

Now that you already know the size of the array it makes sense to preallocate a queue that is large enough to contain all the waiters for the semaphore. This is mainly a performance optimization as now there won't be any need to reallocate the queue.
